class ascii_chars:
	#ASCII Table:

	#Useable Control Character Codes:
	tab = "\t"	#  9 = Horizontal Tab --- 'tab'
	newline = "\n"	#  10 = Line Feed --- 'enter' (recommended)
	carriageReturn = "\r"	#  13 = Carriage Return --- 'enter' (not recommended)

	#Printable Character Codes:
	space = chr(32)	#  " "
	exclamation = chr(33)	#  "!"
	dblQuote = chr(34)	#  """
	number = chr(35)	#  "#"
	dollar = chr(36)	#  "$"
	percent = chr(37)	#  "%"
	ampersand = chr(38)	#  "&"
	singleQuote = chr(39)	#  "'"
	openParentheses = chr(40)	#  "("
	closeParentheses = chr(41)	#  ")"
	asterisk = chr(42)	#  "*"
	plus = chr(43)	#  "+"
	comma = chr(44)	#  ","
	hyphen = chr(45)	#  "-"
	period = chr(46)	#  "."
	slash = chr(47)	#  "/"
	zero = chr(48)	#  "0"
	one = chr(49)	#  "1"
	two = chr(50)	#  "2"
	three = chr(51)	#  "3"
	four = chr(52)	#  "4"
	five = chr(53)	#  "5"
	six = chr(54)	#  "6"
	seven = chr(55)	#  "7"
	eight = chr(56)	#  "8"
	nine = chr(57)	#  "9"
	colon = chr(58)	#  ":"
	semicolon = chr(59)	#  ";"
	lessThan = chr(60)	#  "<"
	equals = chr(61)	#  "="
	greaterThan = chr(62)	#  ">"
	question = chr(63)	#  "?"
	at = chr(64)	#  "@"
	A = chr(65)	#  "A"
	B = chr(66)	#  "B"
	C = chr(67)	#  "C"
	D = chr(68)	#  "D"
	E = chr(69)	#  "E"
	F = chr(70)	#  "F"
	G = chr(71)	#  "G"
	H = chr(72)	#  "H"
	I = chr(73)	#  "I"
	J = chr(74)	#  "J"
	K = chr(75)	#  "K"
	L = chr(76)	#  "L"
	M = chr(77)	#  "M"
	N = chr(78)	#  "N"
	O = chr(79)	#  "O"
	P = chr(80)	#  "P"
	Q = chr(81)	#  "Q"
	R = chr(82)	#  "R"
	S = chr(83)	#  "S"
	T = chr(84)	#  "T"
	U = chr(85)	#  "U"
	V = chr(86)	#  "V"
	W = chr(87)	#  "W"
	X = chr(88)	#  "X"
	Y = chr(89)	#  "Y"
	Z = chr(90)	#  "Z"
	openBracket = chr(91)	#  "["
	backslash = chr(92)	#  "\"
	closeBracket = chr(93)	#  "]"
	caret = chr(94)	#  "^"
	underscore = chr(95)	#  "_"
	grave = chr(96)	#  "`"
	a = chr(97)	#  "a"
	b = chr(98)	#  "b"
	c = chr(99)	#  "c"
	d = chr(100)	#  "d"
	e = chr(101)	#  "e"
	f = chr(102)	#  "f"
	g = chr(103)	#  "g"
	h = chr(104)	#  "h"
	i = chr(105)	#  "i"
	j = chr(106)	#  "j"
	k = chr(107)	#  "k"
	l = chr(108)	#  "l"
	m = chr(109)	#  "m"
	n = chr(110)	#  "n"
	o = chr(111)	#  "o"
	p = chr(112)	#  "p"
	q = chr(113)	#  "q"
	r = chr(114)	#  "r"
	s = chr(115)	#  "s"
	t = chr(116)	#  "t"
	u = chr(117)	#  "u"
	v = chr(118)	#  "v"
	w = chr(119)	#  "w"
	x = chr(120)	#  "x"
	y = chr(121)	#  "y"
	z = chr(122)	#  "z"
	openCurlyBracket = chr(123)	#  "{"
	verticalBar = chr(124)	#  "|"
	closeCurlyBracket = chr(125)	#  "}"
	tilde = chr(126)	#  "~"
